name: aitrivia
version: "1.0.0"
config-version: 2

profile: aitrivia

model-paths: ["models"]

models:
  aitrivia:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: gold