name: aitrivia
version: "1.0.0"
config-version: 2

profile: aitrivia

model-paths: ["./src/models/"]

models:
  aitrivia:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table